// <auto-generated />
namespace Data_Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrationV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationV2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104261743465_migrationV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
